export const actionTypes = {
  CREATE_TODO: "CREATE_TODO",
  FETCH_TODOS: "FETCH_TODOS",
  UPDATE_TODO: "UPDATE_TODO",
  CHECK_TODO: "CHECK_TODO",
  DELETE_TODO: "DELETE_TODO",
  SIGN_UP: "SIGN_UP",
  SIGN_IN: "SIGN_IN",
  LOAD_USER: "LOAD_USER",
  SIGN_OUT: "SIGN_OUT"
};
